/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "accent-colorsgold-200": "var(--accent-colorsgold-200)",
        "accent-colorsorange-400": "var(--accent-colorsorange-400)",
        "canvas-colorsmc-black": "var(--canvas-colorsmc-black)",
        "canvas-colorswhite": "var(--canvas-colorswhite)",
        "deborahrevelers-100": "var(--deborahrevelers-100)",
        "deborahrevelers-200": "var(--deborahrevelers-200)",
        "deborahrevelers-400": "var(--deborahrevelers-400)",
        "deborahrevelers-600": "var(--deborahrevelers-600)",
        "flofuturist-100": "var(--flofuturist-100)",
        "flofuturist-200": "var(--flofuturist-200)",
        "flofuturist-400": "var(--flofuturist-400)",
        "flofuturist-600": "var(--flofuturist-600)",
        "jessica-pplanners-100": "var(--jessica-pplanners-100)",
        "jessica-pplanners-200": "var(--jessica-pplanners-200)",
        "jessica-pplanners-400": "var(--jessica-pplanners-400)",
        "jessica-pplanners-600": "var(--jessica-pplanners-600)",
        "joseexplorers-100": "var(--joseexplorers-100)",
        "joseexplorers-200": "var(--joseexplorers-200)",
        "joseexplorers-400": "var(--joseexplorers-400)",
        "joseexplorers-600": "var(--joseexplorers-600)",
        "kyratranscenders-100": "var(--kyratranscenders-100)",
        "kyratranscenders-200": "var(--kyratranscenders-200)",
        "kyratranscenders-400": "var(--kyratranscenders-400)",
        "kyratranscenders-600": "var(--kyratranscenders-600)",
        "orange-03": "var(--orange-03)",
        "rebeccanewbies-100": "var(--rebeccanewbies-100)",
        "rebeccanewbies-200": "var(--rebeccanewbies-200)",
        "rebeccanewbies-400": "var(--rebeccanewbies-400)",
        "rebeccanewbies-600": "var(--rebeccanewbies-600)",
        "roryovercomers-100": "var(--roryovercomers-100)",
        "roryovercomers-200": "var(--roryovercomers-200)",
        "roryovercomers-400": "var(--roryovercomers-400)",
        "roryovercomers-600": "var(--roryovercomers-600)",
        "russellachievers-100": "var(--russellachievers-100)",
        "russellachievers-200": "var(--russellachievers-200)",
        "russellachievers-400": "var(--russellachievers-400)",
        "russellachievers-600": "var(--russellachievers-600)",
      },
      fontFamily: {
        "body-01": "var(--body-01-font-family)",
        "display-03": "var(--display-03-font-family)",
        "eyebrow-01": "var(--eyebrow-01-font-family)",
        "mark-mc": ["Mark Offc For MC", "sans-serif"],
      },
    },
  },
  plugins: [],
};
